services:
  backend:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: always
    # volumes removed for backend
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
