// // equest: <ref *3> ClientRequest {
// //     _events: [Object: null prototype] {
// //       abort: [Function (anonymous)],
// //       aborted: [Function (anonymous)],
// //       connect: [Function (anonymous)],
// //       error: [Function (anonymous)],
// //       socket: [Function (anonymous)],
// //       timeout: [Function (anonymous)],
// //       finish: [Function: requestOnFinish]
// //     },
// //     _eventsCount: 7,
// //     _maxListeners: undefined,
// //     outputData: [],
// //     outputSize: 0,
// //     writable: true,
// //     destroyed: true,
// //     _last: false,
// //     chunkedEncoding: false,
// //     shouldKeepAlive: true,
// //     maxRequestsOnConnectionReached: false,
// //     _defaultKeepAlive: true,
// //     useChunkedEncodingByDefault: true,
// //     sendDate: false,
// //     _removedConnection: false,
// //     _removedContLen: false,
// //     _removedTE: false,
// //     strictContentLength: false,
// //     _contentLength: 97,
// //     _hasBody: true,
// //     _trailer: '',
// //     finished: true,
// //     _headerSent: true,
// //     _closed: true,
// //     _header: 'POST /user/request-ride HTTP/1.1\r\n' +
// //       'Accept: application/json, text/plain, */*\r\n' +
// //       'Content-Type: application/json\r\n' +
// //       'User-Agent: axios/1.12.2\r\n' +
// //       'Content-Length: 97\r\n' +
// //       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
// //       'Host: localhost:3000\r\n' +
// //       'Connection: keep-alive\r\n' +
// //       '\r\n',
// //     _keepAliveTimeout: 0,
// //     _onPendingData: [Function: nop],
// //     agent: Agent {
// //       _events: [Object: null prototype] {
// //         free: [Function (anonymous)],
// //         newListener: [Function: maybeEnableKeylog]
// //       },
// //       _eventsCount: 2,
// //       _maxListeners: undefined,
// //       defaultPort: 80,
// //       protocol: 'http:',
// //       options: [Object: null prototype] {
// //         keepAlive: true,
// //         scheduling: 'lifo',
// //         timeout: 5000,
// //         noDelay: true,
// //         path: null
// //       },
// //       requests: [Object: null prototype] {},
// //       sockets: [Object: null prototype] {},
// //       freeSockets: [Object: null prototype] {
// //         'localhost:3000:': [
// //           Socket {
// //             connecting: false,
// //             _hadError: false,
// //             _parent: null,
// //             _host: 'localhost',
// //             _closeAfterHandlingError: false,
// //             _events: [Object],
// //             _readableState: [ReadableState],
// //             _writableState: [WritableState],
// //             allowHalfOpen: false,
// //             _maxListeners: undefined,
// //             _eventsCount: 6,
// //             _sockname: null,
// //             _pendingData: null,
// //             _pendingEncoding: '',
// //             server: null,
// //             _server: null,
// //             timeout: 4000,
// //             parser: null,
// //             _httpMessage: null,
// //             autoSelectFamilyAttemptedAddresses: [Array],
// //             [Symbol(async_id_symbol)]: -1,
// //             [Symbol(kHandle)]: [TCP],
// //             [Symbol(lastWriteQueueSize)]: 0,
// //             [Symbol(timeout)]: [Timeout],
// //             [Symbol(kBuffer)]: null,
// //             [Symbol(kBufferCb)]: null,
// //             [Symbol(kBufferGen)]: null,
// //             [Symbol(shapeMode)]: true,
// //             [Symbol(kCapture)]: false,
// //             [Symbol(kSetNoDelay)]: true,
// //             [Symbol(kSetKeepAlive)]: true,
// //             [Symbol(kSetKeepAliveInitialDelay)]: 1,
// //             [Symbol(kBytesRead)]: 0,
// //             [Symbol(kBytesWritten)]: 0
// //           }
// //         ]
// //       },
// //       keepAliveMsecs: 1000,
// //       keepAlive: true,
// //       maxSockets: Infinity,
// //       maxFreeSockets: 256,
// //       scheduling: 'lifo',
// //       maxTotalSockets: Infinity,
// //       totalSocketCount: 1,
// //       [Symbol(shapeMode)]: false,
// //       [Symbol(kCapture)]: false
// //     },
// //     socketPath: undefined,
// //     method: 'POST',
// //     maxHeaderSize: undefined,
// //     insecureHTTPParser: undefined,
// //     joinDuplicateHeaders: undefined,
// //     path: '/user/request-ride',
// //     _ended: true,
// //     res: IncomingMessage {
// //       _events: {
// //         close: undefined,
// //         error: [Function: handleStreamError],
// //         data: [Function: handleStreamData],
// //         end: [ [Function: responseOnEnd], [Function: handleStreamEnd] ],
// //         readable: undefined,
// //         finish: undefined,
// //         aborted: [Function: handlerStreamAborted]
// //       },
// //       _readableState: ReadableState {
// //         highWaterMark: 65536,
// //         buffer: [],
// //         bufferIndex: 0,
// //         length: 0,
// //         pipes: [],
// //         awaitDrainWriters: null,
// //         [Symbol(kState)]: 194779004
// //       },
// //       _maxListeners: undefined,
// //       socket: null,
// //       httpVersionMajor: 1,
// //       httpVersionMinor: 1,
// //       httpVersion: '1.1',
// //       complete: true,
// //       rawHeaders: [
// //         'X-Powered-By',
// //         'Express',
// //         'Access-Control-Allow-Origin',
// //         '*',
// //         'Content-Type',
// //         'application/json; charset=utf-8',
// //         'Content-Length',
// //         '33',
// //         'ETag',
// //         'W/"21-u8tno/8IdqEY6PFcopkQe0syfE4"',
// //         'Date',
// //         'Mon, 12 Jan 2026 02:38:18 GMT',
// //         'Connection',
// //         'keep-alive',
// //         'Keep-Alive',
// //         'timeout=5'
// //       ],
// //       rawTrailers: [],
// //       joinDuplicateHeaders: undefined,
// //       aborted: false,
// //       upgrade: false,
// //       url: '',
// //       method: null,
// //       statusCode: 500,
// //       statusMessage: 'Internal Server Error',
// //       client: <ref *1> Socket {
// //         connecting: false,
// //         _hadError: false,
// //         _parent: null,
// //         _host: 'localhost',
// //         _closeAfterHandlingError: false,
// //         _events: {
// //           close: [Function: onClose],
// //           error: [Function: bound onceWrapper] {
// //             listener: [Function: freeSocketErrorListener]
// //           },
// //           prefinish: undefined,
// //           finish: undefined,
// //           drain: undefined,
// //           data: undefined,
// //           end: [Function: onReadableStreamEnd],
// //           readable: undefined,
// //           connect: undefined,
// //           free: [Function: onFree],
// //           timeout: [Function: onTimeout],
// //           agentRemove: [Function: onRemove]
// //         },
// //         _readableState: ReadableState {
// //           highWaterMark: 65536,
// //           buffer: [],
// //           bufferIndex: 0,
// //           length: 0,
// //           pipes: [],
// //           awaitDrainWriters: null,
// //           [Symbol(kState)]: 60303620
// //         },
// //         _writableState: WritableState {
// //           highWaterMark: 65536,
// //           length: 0,
// //           corked: 0,
// //           onwrite: [Function: bound onwrite],
// //           writelen: 0,
// //           bufferedIndex: 0,
// //           pendingcb: 0,
// //           [Symbol(kState)]: 17563908,
// //           [Symbol(kBufferedValue)]: null,
// //           [Symbol(kWriteCbValue)]: null
// //         },
// //         allowHalfOpen: false,
// //         _maxListeners: undefined,
// //         _eventsCount: 6,
// //         _sockname: null,
// //         _pendingData: null,
// //         _pendingEncoding: '',
// //         server: null,
// //         _server: null,
// //         timeout: 4000,
// //         parser: null,
// //         _httpMessage: null,
// //         autoSelectFamilyAttemptedAddresses: [ '::1:3000' ],
// //         [Symbol(async_id_symbol)]: -1,
// //         [Symbol(kHandle)]: TCP {
// //           reading: true,
// //           onconnection: null,
// //           [Symbol(owner_symbol)]: [Circular *1]
// //         },
// //         [Symbol(lastWriteQueueSize)]: 0,
// //         [Symbol(timeout)]: <ref *2> Timeout {
// //           _idleTimeout: 4000,
// //           _idlePrev: TimersList {
// //             _idleNext: [Circular *2],
// //             _idlePrev: [Circular *2],
// //             expiry: 100657,
// //             id: -9007199254739165,
// //             msecs: 4000,
// //             priorityQueuePosition: 5
// //           },
// //           _idleNext: TimersList {
// //             _idleNext: [Circular *2],
// //             _idlePrev: [Circular *2],
// //             expiry: 100657,
// //             id: -9007199254739165,
// //             msecs: 4000,
// //             priorityQueuePosition: 5
// //           },
// //           _idleStart: 96657,
// //           _onTimeout: [Function: bound ],
// //           _timerArgs: undefined,
// //           _repeat: null,
// //           _destroyed: false,
// //           [Symbol(refed)]: false,
// //           [Symbol(kHasPrimitive)]: false,
// //           [Symbol(asyncId)]: 4017,
// //           [Symbol(triggerId)]: 4015,
// //           [Symbol(kAsyncContextFrame)]: undefined
// //         },
// //         [Symbol(kBuffer)]: null,
// //         [Symbol(kBufferCb)]: null,
// //         [Symbol(kBufferGen)]: null,
// //         [Symbol(shapeMode)]: true,
// //         [Symbol(kCapture)]: false,
// //         [Symbol(kSetNoDelay)]: true,
// //         [Symbol(kSetKeepAlive)]: true,
// //         [Symbol(kSetKeepAliveInitialDelay)]: 1,
// //         [Symbol(kBytesRead)]: 0,
// //         [Symbol(kBytesWritten)]: 0
// //       },
// //       _consuming: false,
// //       _dumped: false,
// //       req: [Circular *3],
// //       _eventsCount: 4,
// //       responseUrl: 'http://localhost:3000/user/request-ride',
// //       redirects: [],
// //       [Symbol(shapeMode)]: true,
// //       [Symbol(kCapture)]: false,
// //       [Symbol(kHeaders)]: {
// //         'x-powered-by': 'Express',
// //         'access-control-allow-origin': '*',
// //         'content-type': 'application/json; charset=utf-8',
// //         'content-length': '33',
// //         etag: 'W/"21-u8tno/8IdqEY6PFcopkQe0syfE4"',
// //         date: 'Mon, 12 Jan 2026 02:38:18 GMT',
// //         connection: 'keep-alive',
// //         'keep-alive': 'timeout=5'
// //       },
// //       [Symbol(kHeadersCount)]: 16,
// //       [Symbol(kTrailers)]: null,
// //       [Symbol(kTrailersCount)]: 0
// //     },
// //     aborted: false,
// //     timeoutCb: null,
// //     upgradeOrConnect: false,
// //     parser: null,
// //     maxHeadersCount: null,
// //     reusedSocket: false,
// //     host: 'localhost',
// //     protocol: 'http:',
// //     _redirectable: Writable {
// //       _events: {
// //         close: undefined,
// //         error: [Function: handleRequestError],
// //         prefinish: undefined,
// //         finish: undefined,
// //         drain: undefined,
// //         response: [Function: handleResponse],
// //         socket: [Function: handleRequestSocket]
// //       },
// //       _writableState: WritableState {
// //         highWaterMark: 65536,
// //         length: 0,
// //         corked: 0,
// //         onwrite: [Function: bound onwrite],
// //         writelen: 0,
// //         bufferedIndex: 0,
// //         pendingcb: 0,
// //         [Symbol(kState)]: 17580812,
// //         [Symbol(kBufferedValue)]: null
// //       },
// //       _maxListeners: undefined,
// //       _options: {
// //         maxRedirects: 21,
// //         maxBodyLength: Infinity,
// //         protocol: 'http:',
// //         path: '/user/request-ride',
// //         method: 'POST',
// //         headers: [Object: null prototype] {
// //           Accept: 'application/json, text/plain, */*',
// //           'Content-Type': 'application/json',
// //           'User-Agent': 'axios/1.12.2',
// //           'Content-Length': '97',
// //           'Accept-Encoding': 'gzip, compress, deflate, br'
// //         },
// //         agents: { http: undefined, https: undefined },
// //         auth: undefined,
// //         family: undefined,
// //         beforeRedirect: [Function: dispatchBeforeRedirect],
// //         beforeRedirects: { proxy: [Function: beforeRedirect] },
// //         hostname: 'localhost',
// //         port: '3000',
// //         agent: undefined,
// //         nativeProtocols: {
// //           'http:': {
// //             _connectionListener: [Function: connectionListener],
// //             METHODS: [Array],
// //             STATUS_CODES: [Object],
// //             Agent: [Function],
// //             ClientRequest: [Function: ClientRequest],
// //             IncomingMessage: [Function: IncomingMessage],
// //             OutgoingMessage: [Function: OutgoingMessage],
// //             Server: [Function: Server],
// //             ServerResponse: [Function: ServerResponse],
// //             createServer: [Function: createServer],
// //             validateHeaderName: [Function],
// //             validateHeaderValue: [Function],
// //             get: [Function: get],
// //             request: [Function: request],
// //             setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
// //             maxHeaderSize: [Getter],
// //             globalAgent: [Getter/Setter],
// //             WebSocket: [Getter],
// //             CloseEvent: [Getter],
// //             MessageEvent: [Getter]
// //           },
// //           'https:': {
// //             Agent: [Function: Agent],
// //             globalAgent: [Agent],
// //             Server: [Function: Server],
// //             createServer: [Function: createServer],
// //             get: [Function: get],
// //             request: [Function: request]
// //           }
// //         },
// //         pathname: '/user/request-ride'
// //       },
// //       _ended: true,
// //       _ending: true,
// //       _redirectCount: 0,
// //       _redirects: [],
// //       _requestBodyLength: 97,
// //       _requestBodyBuffers: [],
// //       _eventsCount: 3,
// //       _onNativeResponse: [Function (anonymous)],
// //       _currentRequest: [Circular *3],
// //       _currentUrl: 'http://localhost:3000/user/request-ride',
// //       [Symbol(shapeMode)]: true,
// //       [Symbol(kCapture)]: false
// //     },
// //     [Symbol(shapeMode)]: false,
// //     [Symbol(kCapture)]: false,
// //     [Symbol(kBytesWritten)]: 0,
// //     [Symbol(kNeedDrain)]: false,
// //     [Symbol(corked)]: 0,
// //     [Symbol(kChunkedBuffer)]: [],
// //     [Symbol(kChunkedLength)]: 0,
// //     [Symbol(kSocket)]: <ref *1> Socket {
// //       connecting: false,
// //       _hadError: false,
// //       _parent: null,
// //       _host: 'localhost',
// //       _closeAfterHandlingError: false,
// //       _events: {
// //         close: [Function: onClose],
// //         error: [Function: bound onceWrapper] {
// //           listener: [Function: freeSocketErrorListener]
// //         },
// //         prefinish: undefined,
// //         finish: undefined,
// //         drain: undefined,
// //         data: undefined,
// //         end: [Function: onReadableStreamEnd],
// //         readable: undefined,
// //         connect: undefined,
// //         free: [Function: onFree],
// //         timeout: [Function: onTimeout],
// //         agentRemove: [Function: onRemove]
// //       },
// //       _readableState: ReadableState {
// //         highWaterMark: 65536,
// //         buffer: [],
// //         bufferIndex: 0,
// //         length: 0,
// //         pipes: [],
// //         awaitDrainWriters: null,
// //         [Symbol(kState)]: 60303620
// //       },
// //       _writableState: WritableState {
// //         highWaterMark: 65536,
// //         length: 0,
// //         corked: 0,
// //         onwrite: [Function: bound onwrite],
// //         writelen: 0,
// //         bufferedIndex: 0,
// //         pendingcb: 0,
// //         [Symbol(kState)]: 17563908,
// //         [Symbol(kBufferedValue)]: null,
// //         [Symbol(kWriteCbValue)]: null
// //       },
// //       allowHalfOpen: false,
// //       _maxListeners: undefined,
// //       _eventsCount: 6,
// //       _sockname: null,
// //       _pendingData: null,
// //       _pendingEncoding: '',
// //       server: null,
// //       _server: null,
// //       timeout: 4000,
// //       parser: null,
// //       _httpMessage: null,
// //       autoSelectFamilyAttemptedAddresses: [ '::1:3000' ],
// //       [Symbol(async_id_symbol)]: -1,
// //       [Symbol(kHandle)]: TCP {
// //         reading: true,
// //         onconnection: null,
// //         [Symbol(owner_symbol)]: [Circular *1]
// //       },
// //       [Symbol(lastWriteQueueSize)]: 0,
// //       [Symbol(timeout)]: <ref *2> Timeout {
// //         _idleTimeout: 4000,
// //         _idlePrev: TimersList {
// //           _idleNext: [Circular *2],
// //           _idlePrev: [Circular *2],
// //           expiry: 100657,
// //           id: -9007199254739165,
// //           msecs: 4000,
// //           priorityQueuePosition: 5
// //         },
// //         _idleNext: TimersList {
// //           _idleNext: [Circular *2],
// //           _idlePrev: [Circular *2],
// //           expiry: 100657,
// //           id: -9007199254739165,
// //           msecs: 4000,
// //           priorityQueuePosition: 5
// //         },
// //         _idleStart: 96657,
// //         _onTimeout: [Function: bound ],
// //         _timerArgs: undefined,
// //         _repeat: null,
// //         _destroyed: false,
// //         [Symbol(refed)]: false,
// //         [Symbol(kHasPrimitive)]: false,
// //         [Symbol(asyncId)]: 4017,
// //         [Symbol(triggerId)]: 4015,
// //         [Symbol(kAsyncContextFrame)]: undefined
// //       },
// //       [Symbol(kBuffer)]: null,
// //       [Symbol(kBufferCb)]: null,
// //       [Symbol(kBufferGen)]: null,
// //       [Symbol(shapeMode)]: true,
// //       [Symbol(kCapture)]: false,
// //       [Symbol(kSetNoDelay)]: true,
// //       [Symbol(kSetKeepAlive)]: true,
// //       [Symbol(kSetKeepAliveInitialDelay)]: 1,
// //       [Symbol(kBytesRead)]: 0,
// //       [Symbol(kBytesWritten)]: 0
// //     },
// //     [Symbol(kOutHeaders)]: [Object: null prototype] {
// //       accept: [ 'Accept', 'application/json, text/plain, */*' ],
// //       'content-type': [ 'Content-Type', 'application/json' ],
// //       'user-agent': [ 'User-Agent', 'axios/1.12.2' ],
// //       'content-length': [ 'Content-Length', '97' ],
// //       'accept-encoding': [ 'Accept-Encoding', 'gzip, compress, deflate, br' ],
// //       host: [ 'Host', 'localhost:3000' ]
// //     },
// //     [Symbol(errored)]: null,
// //     [Symbol(kHighWaterMark)]: 65536,
// //     [Symbol(kRejectNonStandardBodyWrites)]: false,
// //     [Symbol(kUniqueHeaders)]: null
// //   },
// //   response: {
// //     status: 500,
// //     statusText: 'Internal Server Error',
// //     headers: Object [AxiosHeaders] {
// //       'x-powered-by': 'Express',
// //       'access-control-allow-origin': '*',
// //       'content-type': 'application/json; charset=utf-8',
// //       'content-length': '33',
// //       etag: 'W/"21-u8tno/8IdqEY6PFcopkQe0syfE4"',
// //       date: 'Mon, 12 Jan 2026 02:38:18 GMT',
// //       connection: 'keep-alive',
// //       'keep-alive': 'timeout=5'
// //     },
// //     config: {
// //       transitional: {
// //         silentJSONParsing: true,
// //         forcedJSONParsing: true,
// //         clarifyTimeoutError: false
// //       },
// //       adapter: [ 'xhr', 'http', 'fetch' ],
// //       transformRequest: [ [Function: transformRequest] ],
// //       transformResponse: [ [Function: transformResponse] ],
// //       timeout: 0,
// //       xsrfCookieName: 'XSRF-TOKEN',
// //       xsrfHeaderName: 'X-XSRF-TOKEN',
// //       maxContentLength: -1,
// //       maxBodyLength: -1,
// //       env: {
// //         FormData: [Function: FormData] [FormData] {
// //           LINE_BREAK: '\r\n',
// //           DEFAULT_CONTENT_TYPE: 'application/octet-stream'
// //         },
// //         Blob: [class Blob]
// //       },
// //       validateStatus: [Function: validateStatus],
// //       headers: Object [AxiosHeaders] {
// //         Accept: 'application/json, text/plain, */*',
// //         'Content-Type': 'application/json',
// //         'User-Agent': 'axios/1.12.2',
// //         'Content-Length': '97',
// //         'Accept-Encoding': 'gzip, compress, deflate, br'
// //       },
// //       method: 'post',
// //       url: 'http://localhost:3000/user/request-ride',
// //       data: '{"chatId":7175509887,"phone":992707255,"location":{"lat":41.023347,"lon":71.825678},"type":"bot"}',
// //       allowAbsoluteUrls: true
// //     },
// //     request: <ref *3> ClientRequest {
// //       _events: [Object: null prototype] {
// //         abort: [Function (anonymous)],
// //         aborted: [Function (anonymous)],
// //         connect: [Function (anonymous)],
// //         error: [Function (anonymous)],
// //         socket: [Function (anonymous)],
// //         timeout: [Function (anonymous)],
// //         finish: [Function: requestOnFinish]
// //       },
// //       _eventsCount: 7,
// //       _maxListeners: undefined,
// //       outputData: [],
// //       outputSize: 0,
// //       writable: true,
// //       destroyed: true,
// //       _last: false,
// //       chunkedEncoding: false,
// //       shouldKeepAlive: true,
// //       maxRequestsOnConnectionReached: false,
// //       _defaultKeepAlive: true,
// //       useChunkedEncodingByDefault: true,
// //       sendDate: false,
// //       _removedConnection: false,
// //       _removedContLen: false,
// //       _removedTE: false,
// //       strictContentLength: false,
// //       _contentLength: 97,
// //       _hasBody: true,
// //       _trailer: '',
// //       finished: true,
// //       _headerSent: true,
// //       _closed: true,
// //       _header: 'POST /user/request-ride HTTP/1.1\r\n' +
// //         'Accept: application/json, text/plain, */*\r\n' +
// //         'Content-Type: application/json\r\n' +
// //         'User-Agent: axios/1.12.2\r\n' +
// //         'Content-Length: 97\r\n' +
// //         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
// //         'Host: localhost:3000\r\n' +
// //         'Connection: keep-alive\r\n' +
// //         '\r\n',
// //       _keepAliveTimeout: 0,
// //       _onPendingData: [Function: nop],
// //       agent: Agent {
// //         _events: [Object: null prototype] {
// //           free: [Function (anonymous)],
// //           newListener: [Function: maybeEnableKeylog]
// //         },
// //         _eventsCount: 2,
// //         _maxListeners: undefined,
// //         defaultPort: 80,
// //         protocol: 'http:',
// //         options: [Object: null prototype] {
// //           keepAlive: true,
// //           scheduling: 'lifo',
// //           timeout: 5000,
// //           noDelay: true,
// //           path: null
// //         },
// //         requests: [Object: null prototype] {},
// //         sockets: [Object: null prototype] {},
// //         freeSockets: [Object: null prototype] { 'localhost:3000:': [ [Socket] ] },
// //         keepAliveMsecs: 1000,
// //         keepAlive: true,
// //         maxSockets: Infinity,
// //         maxFreeSockets: 256,
// //         scheduling: 'lifo',
// //         maxTotalSockets: Infinity,
// //         totalSocketCount: 1,
// //         [Symbol(shapeMode)]: false,
// //         [Symbol(kCapture)]: false
// //       },
// //       socketPath: undefined,
// //       method: 'POST',
// //       maxHeaderSize: undefined,
// //       insecureHTTPParser: undefined,
// //       joinDuplicateHeaders: undefined,
// //       path: '/user/request-ride',
// //       _ended: true,
// //       res: IncomingMessage {
// //         _events: {
// //           close: undefined,
// //           error: [Function: handleStreamError],
// //           data: [Function: handleStreamData],
// //           end: [ [Function: responseOnEnd], [Function: handleStreamEnd] ],
// //           readable: undefined,
// //           finish: undefined,
// //           aborted: [Function: handlerStreamAborted]
// //         },
// //         _readableState: ReadableState {
// //           highWaterMark: 65536,
// //           buffer: [],
// //           bufferIndex: 0,
// //           length: 0,
// //           pipes: [],
// //           awaitDrainWriters: null,
// //           [Symbol(kState)]: 194779004
// //         },
// //         _maxListeners: undefined,
// //         socket: null,
// //         httpVersionMajor: 1,
// //         httpVersionMinor: 1,
// //         httpVersion: '1.1',
// //         complete: true,
// //         rawHeaders: [
// //           'X-Powered-By',
// //           'Express',
// //           'Access-Control-Allow-Origin',
// //           '*',
// //           'Content-Type',
// //           'application/json; charset=utf-8',
// //           'Content-Length',
// //           '33',
// //           'ETag',
// //           'W/"21-u8tno/8IdqEY6PFcopkQe0syfE4"',
// //           'Date',
// //           'Mon, 12 Jan 2026 02:38:18 GMT',
// //           'Connection',
// //           'keep-alive',
// //           'Keep-Alive',
// //           'timeout=5'
// //         ],
// //         rawTrailers: [],
// //         joinDuplicateHeaders: undefined,
// //         aborted: false,
// //         upgrade: false,
// //         url: '',
// //         method: null,
// //         statusCode: 500,
// //         statusMessage: 'Internal Server Error',
// //         client: <ref *1> Socket {
// //           connecting: false,
// //           _hadError: false,
// //           _parent: null,
// //           _host: 'localhost',
// //           _closeAfterHandlingError: false,
// //           _events: {
// //             close: [Function: onClose],
// //             error: [Function],
// //             prefinish: undefined,
// //             finish: undefined,
// //             drain: undefined,
// //             data: undefined,
// //             end: [Function: onReadableStreamEnd],
// //             readable: undefined,
// //             connect: undefined,
// //             free: [Function: onFree],
// //             timeout: [Function: onTimeout],
// //             agentRemove: [Function: onRemove]
// //           },
// //           _readableState: ReadableState {
// //             highWaterMark: 65536,
// //             buffer: [],
// //             bufferIndex: 0,
// //             length: 0,
// //             pipes: [],
// //             awaitDrainWriters: null,
// //             [Symbol(kState)]: 60303620
// //           },
// //           _writableState: WritableState {
// //             highWaterMark: 65536,
// //             length: 0,
// //             corked: 0,
// //             onwrite: [Function: bound onwrite],
// //             writelen: 0,
// //             bufferedIndex: 0,
// //             pendingcb: 0,
// //             [Symbol(kState)]: 17563908,
// //             [Symbol(kBufferedValue)]: null,
// //             [Symbol(kWriteCbValue)]: null
// //           },
// //           allowHalfOpen: false,
// //           _maxListeners: undefined,
// //           _eventsCount: 6,
// //           _sockname: null,
// //           _pendingData: null,
// //           _pendingEncoding: '',
// //           server: null,
// //           _server: null,
// //           timeout: 4000,
// //           parser: null,
// //           _httpMessage: null,
// //           autoSelectFamilyAttemptedAddresses: [ '::1:3000' ],
// //           [Symbol(async_id_symbol)]: -1,
// //           [Symbol(kHandle)]: TCP {
// //             reading: true,
// //             onconnection: null,
// //             [Symbol(owner_symbol)]: [Circular *1]
// //           },
// //           [Symbol(lastWriteQueueSize)]: 0,
// //           [Symbol(timeout)]: <ref *2> Timeout {
// //             _idleTimeout: 4000,
// //             _idlePrev: [TimersList],
// //             _idleNext: [TimersList],
// //             _idleStart: 96657,
// //             _onTimeout: [Function: bound ],
// //             _timerArgs: undefined,
// //             _repeat: null,
// //             _destroyed: false,
// //             [Symbol(refed)]: false,
// //             [Symbol(kHasPrimitive)]: false,
// //             [Symbol(asyncId)]: 4017,
// //             [Symbol(triggerId)]: 4015,
// //             [Symbol(kAsyncContextFrame)]: undefined
// //           },
// //           [Symbol(kBuffer)]: null,
// //           [Symbol(kBufferCb)]: null,
// //           [Symbol(kBufferGen)]: null,
// //           [Symbol(shapeMode)]: true,
// //           [Symbol(kCapture)]: false,
// //           [Symbol(kSetNoDelay)]: true,
// //           [Symbol(kSetKeepAlive)]: true,
// //           [Symbol(kSetKeepAliveInitialDelay)]: 1,
// //           [Symbol(kBytesRead)]: 0,
// //           [Symbol(kBytesWritten)]: 0
// //         },
// //         _consuming: false,
// //         _dumped: false,
// //         req: [Circular *3],
// //         _eventsCount: 4,
// //         responseUrl: 'http://localhost:3000/user/request-ride',
// //         redirects: [],
// //         [Symbol(shapeMode)]: true,
// //         [Symbol(kCapture)]: false,
// //         [Symbol(kHeaders)]: {
// //           'x-powered-by': 'Express',
// //           'access-control-allow-origin': '*',
// //           'content-type': 'application/json; charset=utf-8',
// //           'content-length': '33',
// //           etag: 'W/"21-u8tno/8IdqEY6PFcopkQe0syfE4"',
// //           date: 'Mon, 12 Jan 2026 02:38:18 GMT',
// //           connection: 'keep-alive',
// //           'keep-alive': 'timeout=5'
// //         },
// //         [Symbol(kHeadersCount)]: 16,
// //         [Symbol(kTrailers)]: null,
// //         [Symbol(kTrailersCount)]: 0
// //       },
// //       aborted: false,
// //       timeoutCb: null,
// //       upgradeOrConnect: false,
// //       parser: null,
// //       maxHeadersCount: null,
// //       reusedSocket: false,
// //       host: 'localhost',
// //       protocol: 'http:',
// //       _redirectable: Writable {
// //         _events: {
// //           close: undefined,
// //           error: [Function: handleRequestError],
// //           prefinish: undefined,
// //           finish: undefined,
// //           drain: undefined,
// //           response: [Function: handleResponse],
// //           socket: [Function: handleRequestSocket]
// //         },
// //         _writableState: WritableState {
// //           highWaterMark: 65536,
// //           length: 0,
// //           corked: 0,
// //           onwrite: [Function: bound onwrite],
// //           writelen: 0,
// //           bufferedIndex: 0,
// //           pendingcb: 0,
// //           [Symbol(kState)]: 17580812,
// //           [Symbol(kBufferedValue)]: null
// //         },
// //         _maxListeners: undefined,
// //         _options: {
// //           maxRedirects: 21,
// //           maxBodyLength: Infinity,
// //           protocol: 'http:',
// //           path: '/user/request-ride',
// //           method: 'POST',
// //           headers: [Object: null prototype] {
// //             Accept: 'application/json, text/plain, */*',
// //             'Content-Type': 'application/json',
// //             'User-Agent': 'axios/1.12.2',
// //             'Content-Length': '97',
// //             'Accept-Encoding': 'gzip, compress, deflate, br'
// //           },
// //           agents: { http: undefined, https: undefined },
// //           auth: undefined,
// //           family: undefined,
// //           beforeRedirect: [Function: dispatchBeforeRedirect],
// //           beforeRedirects: { proxy: [Function: beforeRedirect] },
// //           hostname: 'localhost',
// //           port: '3000',
// //           agent: undefined,
// //           nativeProtocols: { 'http:': [Object], 'https:': [Object] },
// //           pathname: '/user/request-ride'
// //         },
// //         _ended: true,
// //         _ending: true,
// //         _redirectCount: 0,
// //         _redirects: [],
// //         _requestBodyLength: 97,
// //         _requestBodyBuffers: [],
// //         _eventsCount: 3,
// //         _onNativeResponse: [Function (anonymous)],
// //         _currentRequest: [Circular *3],
// //         _currentUrl: 'http://localhost:3000/user/request-ride',
// //         [Symbol(shapeMode)]: true,
// //         [Symbol(kCapture)]: false
// //       },
// //       [Symbol(shapeMode)]: false,
// //       [Symbol(kCapture)]: false,
// //       [Symbol(kBytesWritten)]: 0,
// //       [Symbol(kNeedDrain)]: false,
// //       [Symbol(corked)]: 0,
// //       [Symbol(kChunkedBuffer)]: [],
// //       [Symbol(kChunkedLength)]: 0,
// //       [Symbol(kSocket)]: <ref *1> Socket {
// //         connecting: false,
// //         _hadError: false,
// //         _parent: null,
// //         _host: 'localhost',
// //         _closeAfterHandlingError: false,
// //         _events: {
// //           close: [Function: onClose],
// //           error: [Function: bound onceWrapper] {
// //             listener: [Function: freeSocketErrorListener]
// //           },
// //           prefinish: undefined,
// //           finish: undefined,
// //           drain: undefined,
// //           data: undefined,
// //           end: [Function: onReadableStreamEnd],
// //           readable: undefined,
// //           connect: undefined,
// //           free: [Function: onFree],
// //           timeout: [Function: onTimeout],
// //           agentRemove: [Function: onRemove]
// //         },
// //         _readableState: ReadableState {
// //           highWaterMark: 65536,
// //           buffer: [],
// //           bufferIndex: 0,
// //           length: 0,
// //           pipes: [],
// //           awaitDrainWriters: null,
// //           [Symbol(kState)]: 60303620
// //         },
// //         _writableState: WritableState {
// //           highWaterMark: 65536,
// //           length: 0,
// //           corked: 0,
// //           onwrite: [Function: bound onwrite],
// //           writelen: 0,
// //           bufferedIndex: 0,
// //           pendingcb: 0,
// //           [Symbol(kState)]: 17563908,
// //           [Symbol(kBufferedValue)]: null,
// //           [Symbol(kWriteCbValue)]: null
// //         },
// //         allowHalfOpen: false,
// //         _maxListeners: undefined,
// //         _eventsCount: 6,
// //         _sockname: null,
// //         _pendingData: null,
// //         _pendingEncoding: '',
// //         server: null,
// //         _server: null,
// //         timeout: 4000,
// //         parser: null,
// //         _httpMessage: null,
// //         autoSelectFamilyAttemptedAddresses: [ '::1:3000' ],
// //         [Symbol(async_id_symbol)]: -1,
// //         [Symbol(kHandle)]: TCP {
// //           reading: true,
// //           onconnection: null,
// //           [Symbol(owner_symbol)]: [Circular *1]
// //         },
// //         [Symbol(lastWriteQueueSize)]: 0,
// //         [Symbol(timeout)]: <ref *2> Timeout {
// //           _idleTimeout: 4000,
// //           _idlePrev: TimersList {
// //             _idleNext: [Circular *2],
// //             _idlePrev: [Circular *2],
//             expiry: 100657,
//             id: -9007199254739165,
//             msecs: 4000,
//             priorityQueuePosition: 5
//           },
//           _idleNext: TimersList {
//             _idleNext: [Circular *2],
//             _idlePrev: [Circular *2],
//             expiry: 100657,
//             id: -9007199254739165,
//             msecs: 4000,
//             priorityQueuePosition: 5
//           },
//           _idleStart: 96657,
//           _onTimeout: [Function: bound ],
//           _timerArgs: undefined,
//           _repeat: null,
//           _destroyed: false,
//           [Symbol(refed)]: false,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 4017,
//           [Symbol(triggerId)]: 4015,
//           [Symbol(kAsyncContextFrame)]: undefined
//         },
//         [Symbol(kBuffer)]: null,
//         [Symbol(kBufferCb)]: null,
//         [Symbol(kBufferGen)]: null,
//         [Symbol(shapeMode)]: true,
//         [Symbol(kCapture)]: false,
//         [Symbol(kSetNoDelay)]: true,
//         [Symbol(kSetKeepAlive)]: true,
//         [Symbol(kSetKeepAliveInitialDelay)]: 1,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0
//       },
//       [Symbol(kOutHeaders)]: [Object: null prototype] {
//         accept: [ 'Accept', 'application/json, text/plain, */*' ],
//         'content-type': [ 'Content-Type', 'application/json' ],
//         'user-agent': [ 'User-Agent', 'axios/1.12.2' ],
//         'content-length': [ 'Content-Length', '97' ],
//         'accept-encoding': [ 'Accept-Encoding', 'gzip, compress, deflate, br' ],
//         host: [ 'Host', 'localhost:3000' ]
//       },
//       [Symbol(errored)]: null,
//       [Symbol(kHighWaterMark)]: 65536,
//       [Symbol(kRejectNonStandardBodyWrites)]: false,
//       [Symbol(kUniqueHeaders)]: null
//     },
//     data: { error: 'Internal server error' }
//   },
//   status: 500
// }

// Node.js v22.18.0
// ilyosbekibrokhimov@Ilyosbeks-MacBook-Pro-2 osonride_user_bot % 