// src/modules/ride/ride.config.ts
import { RideSearchMode } from "./ride.types";

export const RideConfig = {
    SEARCH_MODE: RideSearchMode.SEQUENTIAL,

    SEARCH_INTERVAL_MS: 5000,
    OFFER_TTL_MS: 10000,
    MAX_SEARCH_TIME_MS: 60000,

    INITIAL_RADIUS_KM: 0.5,
    RADIUS_STEP_KM: 0.5,

    PARALLEL_MAX_DRIVERS: 3,
    PARALLEL_PICK_WINDOW_MS: 500,
    PARALLEL_RADIUS_EXPAND_MS: 15000,

    STAGE_WAIT_MS: 5000,
    STAGE3_BURST_COUNT: 40,
    STAGE4_BATCH_COUNT: 40,
    STAGE4_EXPAND_EVERY_MS: 5000,

    STAGE1_2_RADIUS_KM: 0.8,
    STAGE3_RADIUS_KM: 1.5,
    STAGE1_2_WAIT_MS: 5000,

    RIDE_TTL_SECONDS: 300,
    OFFERED_SET_TTL_SECONDS: 300,

    SEARCH_LOCK_EX_SECONDS: 60,
    SEARCH_LOCK_REFRESH_SECONDS: 60,
} as const;
